### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by DeerSong** [CyanChan/chatroom-nodejs#1]
您好！我在csdn上看到了您的分享，刚刚也尝试运行了您的聊天室demo，很不错！有一点小小的建议，就是加一个package.json，把依赖包写到这里，然后ignore掉node_modules。这样能清爽一些，其他人学习代码时看安装包也会更方便^_^

**Comment by CyanChan** [comment]
谢谢提出的意见，由于学习方向和之前的不大一样。原则上基本不会更新这个项目了。要是有更好的优化代码的方法的话可以push上来合并
